### ISSUE TITLE
[1.20.1]Game stuck

### ISSUE THREAD

**Issue by Git-Reternos** [philoufilou/Logic-Chips#6]
[latest.log](https://github.com/user-attachments/files/18221982/latest.log)

**Comment by ZZZank** [comment]
I didn't see any LogicChips related errors in this log, but instead I saw these lines, which indicate that mixin from `betterchunkloading` is failing, so please remove `betterchunkloading` and try again
```
[21:25:42] [modloading-worker-0/WARN]: Mixin apply failed betterchunkloading.mixins.json:ServerChunkCacheMixin -> net.minecraft.server.level.ServerChunkCache: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/server/level/ServerChunkCache::prioWaiting with priority 200 cannot inject into net/minecraft/server/level/ServerChunkCache::m_7587_(IILnet/minecraft/world/level/chunk/ChunkStatus;Z)Lnet/minecraft/world/level/chunk/ChunkAccess; merged by me.jellysquid.mods.lithium.mixin.world.chunk_access.ServerChunkManagerMixin with priority 1000 [ -> redirect$cib000$prioWaiting(Lnet/minecraft/server/level/ServerChunkCache;IILnet/minecraft/world/level/chunk/ChunkStatus;Z)Ljava/util/concurrent/CompletableFuture; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/server/level/ServerChunkCache::prioWaiting with priority 200 cannot inject into net/minecraft/server/level/ServerChunkCache::m_7587_(IILnet/minecraft/world/level/chunk/ChunkStatus;Z)Lnet/minecraft/world/level/chunk/ChunkAccess; merged by me.jellysquid.mods.lithium.mixin.world.chunk_access.ServerChunkManagerMixin with priority 1000 [ -> redirect$cib000$prioWaiting(Lnet/minecraft/server/level/ServerChunkCache;IILnet/minecraft/world/level/chunk/ChunkStatus;Z)Ljava/util/concurrent/CompletableFuture; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
...
```

**Comment by Git-Reternos** [comment]
New Testing
modlist:
Architectury-9.2.14-forge
JEI-1.20.1-forge-15.20.0.105
Logic Chips-1.20.1-2.2.1-forge
Mouse Tweaks-forge-mc1.20.1-2.25.1
my Game still stuck

**Comment by Git-Reternos** [comment]
[latest.log](https://github.com/user-attachments/files/18224789/latest.log)
![螢幕擷取畫面 2024-12-23 113001](https://github.com/user-attachments/assets/35c315a6-954b-417e-85f2-796b87cc3ac6)

**Comment by ZZZank** [comment]
I've managed to reproduce this issue. When the game stuck, a Netty exception is thrown and printed to `debug.log`, it usually looks like this:
```
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$7 (in module io.netty.common) cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to module io.netty.common
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:571) ~[?:?]
	at io.netty.util.internal.PlatformDependent0$7.run(PlatformDependent0.java:410) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
	at java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
...
```

and depending on the version of java you're using, there might also be (on Java21):
```
java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long,int)
```
or (on Java 17)
```
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
```

But the bad news is that Netty problem is usually a Forge internal problem or some dependency problem (in this case Architectury API) since few mods will touch Netty codes. I will do some more investigation later

**Comment by ZZZank** [comment]
I've made some code changes and it's now working in my testing instance, you can download latest snapshot version here: https://github.com/philoufilou/Logic-Chips/actions/runs/12513582584, please give it a try and see if it works

**Comment by Git-Reternos** [comment]
it fixed in latest version
Thanks you
